/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* top =  1  *)
(* src = "pixelSensorFsm.v:32" *)
module pixelSensorFsm(clk, reset, erase, expose, read, convert);
  (* src = "pixelSensorFsm.v:61" *)
  wire _000_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _001_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _002_;
  wire [1:0] _003_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _004_;
  (* src = "pixelSensorFsm.v:102" *)
  wire [2:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _218_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _219_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _220_;
  wire _221_;
  wire _222_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _223_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _224_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _225_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  (* src = "pixelSensorFsm.v:33" *)
  wire _267_;
  (* src = "pixelSensorFsm.v:38" *)
  wire _268_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _269_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _270_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _271_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _272_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _273_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _274_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _275_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _276_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _277_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _278_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _279_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _280_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _281_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _282_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _283_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _284_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _285_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _286_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _287_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _288_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _289_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _290_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _291_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _292_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _293_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _294_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _295_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _296_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _297_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _298_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _299_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _300_;
  (* src = "pixelSensorFsm.v:35" *)
  wire _301_;
  (* src = "pixelSensorFsm.v:36" *)
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _468_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _469_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _470_;
  (* src = "pixelSensorFsm.v:37" *)
  wire _471_;
  (* src = "pixelSensorFsm.v:34" *)
  wire _472_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _473_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _474_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _500_;
  wire _501_;
  wire _502_;
  wire _503_;
  wire _504_;
  wire _505_;
  wire _506_;
  wire _507_;
  wire _508_;
  wire _509_;
  wire _510_;
  wire _511_;
  wire _512_;
  wire _513_;
  wire _514_;
  wire _515_;
  wire _516_;
  wire _517_;
  (* src = "pixelSensorFsm.v:33" *)
  input clk;
  (* src = "pixelSensorFsm.v:38" *)
  output convert;
  (* src = "pixelSensorFsm.v:57" *)
  wire [31:0] counter;
  (* src = "pixelSensorFsm.v:35" *)
  output erase;
  (* src = "pixelSensorFsm.v:36" *)
  output expose;
  (* src = "pixelSensorFsm.v:56" *)
  wire [2:0] next_state;
  (* src = "pixelSensorFsm.v:37" *)
  output read;
  (* src = "pixelSensorFsm.v:34" *)
  input reset;
  (* src = "pixelSensorFsm.v:56" *)
  wire [2:0] state;
  IVX1_CV _518_ (
    .A(_267_),
    .Y(_266_)
  );
  IVX1_CV _519_ (
    .A(_474_),
    .Y(_463_)
  );
  IVX1_CV _520_ (
    .A(_475_),
    .Y(_464_)
  );
  IVX1_CV _521_ (
    .A(_473_),
    .Y(_465_)
  );
  IVX1_CV _522_ (
    .A(_472_),
    .Y(_466_)
  );
  NDX1_CV _523_ (
    .A(_474_),
    .B(_464_),
    .Y(_467_)
  );
  ORX1_CV _524_ (
    .A(_473_),
    .B(_467_),
    .Y(_303_)
  );
  IVX1_CV _525_ (
    .A(_303_),
    .Y(_304_)
  );
  ANX1_CV _526_ (
    .A(_464_),
    .B(_473_),
    .Y(_305_)
  );
  NDX1_CV _527_ (
    .A(_464_),
    .B(_473_),
    .Y(_306_)
  );
  NDX1_CV _528_ (
    .A(_463_),
    .B(_305_),
    .Y(_307_)
  );
  IVX1_CV _529_ (
    .A(_307_),
    .Y(_308_)
  );
  NDX1_CV _530_ (
    .A(_303_),
    .B(_307_),
    .Y(_309_)
  );
  NRX1_CV _531_ (
    .A(_237_),
    .B(_240_),
    .Y(_310_)
  );
  NRX1_CV _532_ (
    .A(_238_),
    .B(_239_),
    .Y(_311_)
  );
  ANX1_CV _533_ (
    .A(_310_),
    .B(_311_),
    .Y(_312_)
  );
  NRX1_CV _534_ (
    .A(_233_),
    .B(_234_),
    .Y(_313_)
  );
  NRX1_CV _535_ (
    .A(_235_),
    .B(_236_),
    .Y(_314_)
  );
  ANX1_CV _536_ (
    .A(_313_),
    .B(_314_),
    .Y(_315_)
  );
  ANX1_CV _537_ (
    .A(_312_),
    .B(_315_),
    .Y(_316_)
  );
  NRX1_CV _538_ (
    .A(_249_),
    .B(_250_),
    .Y(_317_)
  );
  NRX1_CV _539_ (
    .A(_251_),
    .B(_252_),
    .Y(_318_)
  );
  ANX1_CV _540_ (
    .A(_317_),
    .B(_318_),
    .Y(_319_)
  );
  NRX1_CV _541_ (
    .A(_243_),
    .B(_248_),
    .Y(_320_)
  );
  NRX1_CV _542_ (
    .A(_241_),
    .B(_242_),
    .Y(_321_)
  );
  ANX1_CV _543_ (
    .A(_320_),
    .B(_321_),
    .Y(_322_)
  );
  ANX1_CV _544_ (
    .A(_319_),
    .B(_322_),
    .Y(_323_)
  );
  NRX1_CV _545_ (
    .A(_258_),
    .B(_259_),
    .Y(_324_)
  );
  NRX1_CV _546_ (
    .A(_257_),
    .B(_260_),
    .Y(_325_)
  );
  ANX1_CV _547_ (
    .A(_324_),
    .B(_325_),
    .Y(_326_)
  );
  NRX1_CV _548_ (
    .A(_253_),
    .B(_254_),
    .Y(_327_)
  );
  NRX1_CV _549_ (
    .A(_255_),
    .B(_256_),
    .Y(_328_)
  );
  ANX1_CV _550_ (
    .A(_327_),
    .B(_328_),
    .Y(_329_)
  );
  ANX1_CV _551_ (
    .A(_326_),
    .B(_329_),
    .Y(_330_)
  );
  ANX1_CV _552_ (
    .A(_316_),
    .B(_330_),
    .Y(_331_)
  );
  ANX1_CV _553_ (
    .A(_323_),
    .B(_331_),
    .Y(_332_)
  );
  ANX1_CV _554_ (
    .A(_229_),
    .B(_244_),
    .Y(_333_)
  );
  ANX1_CV _555_ (
    .A(_229_),
    .B(_230_),
    .Y(_334_)
  );
  ANX1_CV _556_ (
    .A(_230_),
    .B(_333_),
    .Y(_335_)
  );
  ANX1_CV _557_ (
    .A(_245_),
    .B(_335_),
    .Y(_336_)
  );
  ANX1_CV _558_ (
    .A(_231_),
    .B(_336_),
    .Y(_337_)
  );
  ANX1_CV _559_ (
    .A(_246_),
    .B(_337_),
    .Y(_338_)
  );
  ANX1_CV _560_ (
    .A(_232_),
    .B(_338_),
    .Y(_339_)
  );
  ANX1_CV _561_ (
    .A(_247_),
    .B(_339_),
    .Y(_340_)
  );
  NDX1_CV _562_ (
    .A(_332_),
    .B(_340_),
    .Y(_341_)
  );
  NDX1_CV _563_ (
    .A(_464_),
    .B(_341_),
    .Y(_342_)
  );
  NDX1_CV _564_ (
    .A(_309_),
    .B(_342_),
    .Y(_343_)
  );
  NRX1_CV _565_ (
    .A(_244_),
    .B(_245_),
    .Y(_344_)
  );
  NRX1_CV _566_ (
    .A(_246_),
    .B(_247_),
    .Y(_345_)
  );
  ANX1_CV _567_ (
    .A(_344_),
    .B(_345_),
    .Y(_346_)
  );
  NRX1_CV _568_ (
    .A(_231_),
    .B(_232_),
    .Y(_347_)
  );
  ANX1_CV _569_ (
    .A(_346_),
    .B(_347_),
    .Y(_348_)
  );
  ANX1_CV _570_ (
    .A(_334_),
    .B(_348_),
    .Y(_349_)
  );
  NDX1_CV _571_ (
    .A(_332_),
    .B(_349_),
    .Y(_350_)
  );
  NDX1_CV _572_ (
    .A(_464_),
    .B(_350_),
    .Y(_351_)
  );
  ANX1_CV _573_ (
    .A(_474_),
    .B(_305_),
    .Y(_352_)
  );
  NDX1_CV _574_ (
    .A(_474_),
    .B(_305_),
    .Y(_353_)
  );
  ORX1_CV _575_ (
    .A(_474_),
    .B(_473_),
    .Y(_354_)
  );
  ORX1_CV _576_ (
    .A(_475_),
    .B(_354_),
    .Y(_355_)
  );
  NDX1_CV _577_ (
    .A(_353_),
    .B(_355_),
    .Y(_356_)
  );
  NDX1_CV _578_ (
    .A(_351_),
    .B(_356_),
    .Y(_357_)
  );
  ANX1_CV _579_ (
    .A(_475_),
    .B(_354_),
    .Y(_358_)
  );
  NDX1_CV _580_ (
    .A(_475_),
    .B(_470_),
    .Y(_359_)
  );
  NDX1_CV _581_ (
    .A(_466_),
    .B(_359_),
    .Y(_360_)
  );
  NRX1_CV _582_ (
    .A(_358_),
    .B(_360_),
    .Y(_361_)
  );
  ANX1_CV _583_ (
    .A(_357_),
    .B(_361_),
    .Y(_362_)
  );
  NDX1_CV _584_ (
    .A(_343_),
    .B(_362_),
    .Y(_226_)
  );
  NDX1_CV _585_ (
    .A(_304_),
    .B(_341_),
    .Y(_363_)
  );
  NDX1_CV _586_ (
    .A(_465_),
    .B(_469_),
    .Y(_364_)
  );
  NDX1_CV _587_ (
    .A(_463_),
    .B(_364_),
    .Y(_365_)
  );
  NDX1_CV _588_ (
    .A(_475_),
    .B(_365_),
    .Y(_366_)
  );
  NDX1_CV _589_ (
    .A(_350_),
    .B(_352_),
    .Y(_367_)
  );
  ANX1_CV _590_ (
    .A(_366_),
    .B(_367_),
    .Y(_368_)
  );
  NDX1_CV _591_ (
    .A(_363_),
    .B(_368_),
    .Y(_369_)
  );
  ANX1_CV _592_ (
    .A(_466_),
    .B(_369_),
    .Y(_225_)
  );
  NDX1_CV _593_ (
    .A(_308_),
    .B(_341_),
    .Y(_370_)
  );
  NDX1_CV _594_ (
    .A(_463_),
    .B(_468_),
    .Y(_371_)
  );
  NDX1_CV _595_ (
    .A(_465_),
    .B(_371_),
    .Y(_372_)
  );
  NDX1_CV _596_ (
    .A(_475_),
    .B(_372_),
    .Y(_373_)
  );
  ANX1_CV _597_ (
    .A(_367_),
    .B(_373_),
    .Y(_374_)
  );
  NDX1_CV _598_ (
    .A(_370_),
    .B(_374_),
    .Y(_375_)
  );
  ANX1_CV _599_ (
    .A(_466_),
    .B(_375_),
    .Y(_224_)
  );
  NRX1_CV _600_ (
    .A(_225_),
    .B(_224_),
    .Y(_376_)
  );
  NDX1_CV _601_ (
    .A(_226_),
    .B(_376_),
    .Y(_377_)
  );
  IVX1_CV _602_ (
    .A(_377_),
    .Y(_378_)
  );
  NRX1_CV _603_ (
    .A(_229_),
    .B(_378_),
    .Y(_269_)
  );
  EOX1_CV _604_ (
    .A(_229_),
    .B(_244_),
    .Y(_379_)
  );
  ANX1_CV _605_ (
    .A(_377_),
    .B(_379_),
    .Y(_280_)
  );
  EOX1_CV _606_ (
    .A(_245_),
    .B(_335_),
    .Y(_380_)
  );
  ANX1_CV _607_ (
    .A(_377_),
    .B(_380_),
    .Y(_294_)
  );
  EOX1_CV _608_ (
    .A(_230_),
    .B(_333_),
    .Y(_381_)
  );
  ANX1_CV _609_ (
    .A(_377_),
    .B(_381_),
    .Y(_291_)
  );
  EOX1_CV _610_ (
    .A(_246_),
    .B(_337_),
    .Y(_382_)
  );
  ANX1_CV _611_ (
    .A(_377_),
    .B(_382_),
    .Y(_296_)
  );
  EOX1_CV _612_ (
    .A(_231_),
    .B(_336_),
    .Y(_383_)
  );
  ANX1_CV _613_ (
    .A(_377_),
    .B(_383_),
    .Y(_295_)
  );
  EOX1_CV _614_ (
    .A(_247_),
    .B(_339_),
    .Y(_384_)
  );
  ANX1_CV _615_ (
    .A(_377_),
    .B(_384_),
    .Y(_298_)
  );
  EOX1_CV _616_ (
    .A(_232_),
    .B(_338_),
    .Y(_385_)
  );
  ANX1_CV _617_ (
    .A(_377_),
    .B(_385_),
    .Y(_297_)
  );
  ANX1_CV _618_ (
    .A(_233_),
    .B(_340_),
    .Y(_386_)
  );
  ANX1_CV _619_ (
    .A(_248_),
    .B(_386_),
    .Y(_387_)
  );
  EOX1_CV _620_ (
    .A(_248_),
    .B(_386_),
    .Y(_388_)
  );
  ANX1_CV _621_ (
    .A(_377_),
    .B(_388_),
    .Y(_300_)
  );
  EOX1_CV _622_ (
    .A(_233_),
    .B(_340_),
    .Y(_389_)
  );
  ANX1_CV _623_ (
    .A(_377_),
    .B(_389_),
    .Y(_299_)
  );
  ANX1_CV _624_ (
    .A(_234_),
    .B(_387_),
    .Y(_390_)
  );
  ANX1_CV _625_ (
    .A(_249_),
    .B(_390_),
    .Y(_391_)
  );
  EOX1_CV _626_ (
    .A(_249_),
    .B(_390_),
    .Y(_392_)
  );
  ANX1_CV _627_ (
    .A(_377_),
    .B(_392_),
    .Y(_271_)
  );
  EOX1_CV _628_ (
    .A(_234_),
    .B(_387_),
    .Y(_393_)
  );
  ANX1_CV _629_ (
    .A(_377_),
    .B(_393_),
    .Y(_270_)
  );
  ANX1_CV _630_ (
    .A(_235_),
    .B(_391_),
    .Y(_394_)
  );
  ORX1_CV _631_ (
    .A(_250_),
    .B(_394_),
    .Y(_395_)
  );
  ANX1_CV _632_ (
    .A(_250_),
    .B(_394_),
    .Y(_396_)
  );
  NRX1_CV _633_ (
    .A(_378_),
    .B(_396_),
    .Y(_397_)
  );
  ANX1_CV _634_ (
    .A(_395_),
    .B(_397_),
    .Y(_273_)
  );
  EOX1_CV _635_ (
    .A(_235_),
    .B(_391_),
    .Y(_398_)
  );
  ANX1_CV _636_ (
    .A(_377_),
    .B(_398_),
    .Y(_272_)
  );
  ANX1_CV _637_ (
    .A(_236_),
    .B(_396_),
    .Y(_399_)
  );
  ANX1_CV _638_ (
    .A(_251_),
    .B(_399_),
    .Y(_400_)
  );
  ORX1_CV _639_ (
    .A(_251_),
    .B(_399_),
    .Y(_401_)
  );
  NDX1_CV _640_ (
    .A(_377_),
    .B(_401_),
    .Y(_402_)
  );
  NRX1_CV _641_ (
    .A(_400_),
    .B(_402_),
    .Y(_275_)
  );
  ORX1_CV _642_ (
    .A(_236_),
    .B(_396_),
    .Y(_403_)
  );
  NDX1_CV _643_ (
    .A(_377_),
    .B(_403_),
    .Y(_404_)
  );
  NRX1_CV _644_ (
    .A(_399_),
    .B(_404_),
    .Y(_274_)
  );
  ANX1_CV _645_ (
    .A(_237_),
    .B(_400_),
    .Y(_405_)
  );
  ANX1_CV _646_ (
    .A(_252_),
    .B(_405_),
    .Y(_406_)
  );
  ORX1_CV _647_ (
    .A(_252_),
    .B(_405_),
    .Y(_407_)
  );
  NDX1_CV _648_ (
    .A(_377_),
    .B(_407_),
    .Y(_408_)
  );
  NRX1_CV _649_ (
    .A(_406_),
    .B(_408_),
    .Y(_277_)
  );
  ORX1_CV _650_ (
    .A(_237_),
    .B(_400_),
    .Y(_409_)
  );
  NDX1_CV _651_ (
    .A(_377_),
    .B(_409_),
    .Y(_410_)
  );
  NRX1_CV _652_ (
    .A(_405_),
    .B(_410_),
    .Y(_276_)
  );
  ANX1_CV _653_ (
    .A(_238_),
    .B(_406_),
    .Y(_411_)
  );
  ANX1_CV _654_ (
    .A(_253_),
    .B(_411_),
    .Y(_412_)
  );
  ORX1_CV _655_ (
    .A(_253_),
    .B(_411_),
    .Y(_413_)
  );
  NDX1_CV _656_ (
    .A(_377_),
    .B(_413_),
    .Y(_414_)
  );
  NRX1_CV _657_ (
    .A(_412_),
    .B(_414_),
    .Y(_279_)
  );
  ORX1_CV _658_ (
    .A(_238_),
    .B(_406_),
    .Y(_415_)
  );
  NDX1_CV _659_ (
    .A(_377_),
    .B(_415_),
    .Y(_416_)
  );
  NRX1_CV _660_ (
    .A(_411_),
    .B(_416_),
    .Y(_278_)
  );
  ANX1_CV _661_ (
    .A(_239_),
    .B(_412_),
    .Y(_417_)
  );
  ANX1_CV _662_ (
    .A(_254_),
    .B(_417_),
    .Y(_418_)
  );
  ORX1_CV _663_ (
    .A(_254_),
    .B(_417_),
    .Y(_419_)
  );
  NDX1_CV _664_ (
    .A(_377_),
    .B(_419_),
    .Y(_420_)
  );
  NRX1_CV _665_ (
    .A(_418_),
    .B(_420_),
    .Y(_282_)
  );
  ORX1_CV _666_ (
    .A(_239_),
    .B(_412_),
    .Y(_421_)
  );
  NDX1_CV _667_ (
    .A(_377_),
    .B(_421_),
    .Y(_422_)
  );
  NRX1_CV _668_ (
    .A(_417_),
    .B(_422_),
    .Y(_281_)
  );
  ANX1_CV _669_ (
    .A(_240_),
    .B(_418_),
    .Y(_423_)
  );
  ANX1_CV _670_ (
    .A(_255_),
    .B(_423_),
    .Y(_424_)
  );
  ORX1_CV _671_ (
    .A(_255_),
    .B(_423_),
    .Y(_425_)
  );
  NDX1_CV _672_ (
    .A(_377_),
    .B(_425_),
    .Y(_426_)
  );
  NRX1_CV _673_ (
    .A(_424_),
    .B(_426_),
    .Y(_284_)
  );
  ORX1_CV _674_ (
    .A(_240_),
    .B(_418_),
    .Y(_427_)
  );
  NDX1_CV _675_ (
    .A(_377_),
    .B(_427_),
    .Y(_428_)
  );
  NRX1_CV _676_ (
    .A(_423_),
    .B(_428_),
    .Y(_283_)
  );
  ANX1_CV _677_ (
    .A(_241_),
    .B(_424_),
    .Y(_429_)
  );
  ANX1_CV _678_ (
    .A(_256_),
    .B(_429_),
    .Y(_430_)
  );
  ORX1_CV _679_ (
    .A(_256_),
    .B(_429_),
    .Y(_431_)
  );
  NDX1_CV _680_ (
    .A(_377_),
    .B(_431_),
    .Y(_432_)
  );
  NRX1_CV _681_ (
    .A(_430_),
    .B(_432_),
    .Y(_286_)
  );
  ORX1_CV _682_ (
    .A(_241_),
    .B(_424_),
    .Y(_433_)
  );
  NDX1_CV _683_ (
    .A(_377_),
    .B(_433_),
    .Y(_434_)
  );
  NRX1_CV _684_ (
    .A(_429_),
    .B(_434_),
    .Y(_285_)
  );
  ANX1_CV _685_ (
    .A(_242_),
    .B(_430_),
    .Y(_435_)
  );
  ANX1_CV _686_ (
    .A(_257_),
    .B(_435_),
    .Y(_436_)
  );
  ORX1_CV _687_ (
    .A(_257_),
    .B(_435_),
    .Y(_437_)
  );
  NDX1_CV _688_ (
    .A(_377_),
    .B(_437_),
    .Y(_438_)
  );
  NRX1_CV _689_ (
    .A(_436_),
    .B(_438_),
    .Y(_288_)
  );
  ORX1_CV _690_ (
    .A(_242_),
    .B(_430_),
    .Y(_439_)
  );
  NDX1_CV _691_ (
    .A(_377_),
    .B(_439_),
    .Y(_440_)
  );
  NRX1_CV _692_ (
    .A(_435_),
    .B(_440_),
    .Y(_287_)
  );
  ANX1_CV _693_ (
    .A(_243_),
    .B(_436_),
    .Y(_441_)
  );
  ANX1_CV _694_ (
    .A(_258_),
    .B(_441_),
    .Y(_442_)
  );
  ORX1_CV _695_ (
    .A(_258_),
    .B(_441_),
    .Y(_443_)
  );
  NDX1_CV _696_ (
    .A(_377_),
    .B(_443_),
    .Y(_444_)
  );
  NRX1_CV _697_ (
    .A(_442_),
    .B(_444_),
    .Y(_290_)
  );
  ORX1_CV _698_ (
    .A(_243_),
    .B(_436_),
    .Y(_445_)
  );
  NDX1_CV _699_ (
    .A(_377_),
    .B(_445_),
    .Y(_446_)
  );
  NRX1_CV _700_ (
    .A(_441_),
    .B(_446_),
    .Y(_289_)
  );
  NDX1_CV _701_ (
    .A(_259_),
    .B(_442_),
    .Y(_447_)
  );
  ENX1_CV _702_ (
    .A(_260_),
    .B(_447_),
    .Y(_448_)
  );
  ANX1_CV _703_ (
    .A(_377_),
    .B(_448_),
    .Y(_293_)
  );
  ORX1_CV _704_ (
    .A(_259_),
    .B(_442_),
    .Y(_449_)
  );
  ANX1_CV _705_ (
    .A(_377_),
    .B(_449_),
    .Y(_450_)
  );
  ANX1_CV _706_ (
    .A(_447_),
    .B(_450_),
    .Y(_292_)
  );
  ANX1_CV _707_ (
    .A(_466_),
    .B(_306_),
    .Y(_221_)
  );
  ANX1_CV _708_ (
    .A(_466_),
    .B(_309_),
    .Y(_222_)
  );
  NDX1_CV _709_ (
    .A(_475_),
    .B(_261_),
    .Y(_451_)
  );
  ANX1_CV _710_ (
    .A(_306_),
    .B(_451_),
    .Y(_452_)
  );
  ANX1_CV _711_ (
    .A(_354_),
    .B(_452_),
    .Y(_218_)
  );
  NDX1_CV _712_ (
    .A(_475_),
    .B(_262_),
    .Y(_453_)
  );
  ANX1_CV _713_ (
    .A(_467_),
    .B(_453_),
    .Y(_454_)
  );
  ANX1_CV _714_ (
    .A(_354_),
    .B(_454_),
    .Y(_220_)
  );
  NDX1_CV _715_ (
    .A(_301_),
    .B(_358_),
    .Y(_455_)
  );
  NDX1_CV _716_ (
    .A(_355_),
    .B(_455_),
    .Y(_219_)
  );
  NDX1_CV _717_ (
    .A(_471_),
    .B(_358_),
    .Y(_456_)
  );
  NDX1_CV _718_ (
    .A(_353_),
    .B(_456_),
    .Y(_223_)
  );
  NDX1_CV _719_ (
    .A(_341_),
    .B(_222_),
    .Y(_457_)
  );
  ANX1_CV _720_ (
    .A(_350_),
    .B(_356_),
    .Y(_458_)
  );
  NDX1_CV _721_ (
    .A(_466_),
    .B(_458_),
    .Y(_459_)
  );
  NDX1_CV _722_ (
    .A(_457_),
    .B(_459_),
    .Y(_460_)
  );
  ORX1_CV _723_ (
    .A(_358_),
    .B(_460_),
    .Y(_461_)
  );
  NDX1_CV _724_ (
    .A(_466_),
    .B(_461_),
    .Y(_227_)
  );
  ORX1_CV _725_ (
    .A(_475_),
    .B(_460_),
    .Y(_462_)
  );
  NDX1_CV _726_ (
    .A(_466_),
    .B(_462_),
    .Y(_228_)
  );
  IVX1_CV _727_ (
    .A(_267_),
    .Y(_263_)
  );
  IVX1_CV _728_ (
    .A(_267_),
    .Y(_264_)
  );
  IVX1_CV _729_ (
    .A(_267_),
    .Y(_265_)
  );
  (* src = "pixelSensorFsm.v:61" *)
  DFSRQNX1_CV _730_ (
    .CK(_514_),
    .D(_004_),
    .Q(read),
    .QN(_508_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:61" *)
  DFSRQNX1_CV _731_ (
    .CK(_515_),
    .D(_000_),
    .Q(convert),
    .QN(_509_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:61" *)
  DFSRQNX1_CV _732_ (
    .CK(_516_),
    .D(_001_),
    .Q(erase),
    .QN(_510_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:61" *)
  DFSRQNX1_CV _733_ (
    .CK(_517_),
    .D(_002_),
    .Q(expose),
    .QN(_511_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  \$_DLATCH_P_  _734_ (
    .D(_005_[0]),
    .E(_006_),
    .Q(state[0])
  );
  (* src = "pixelSensorFsm.v:102" *)
  \$_DLATCH_P_  _735_ (
    .D(_005_[1]),
    .E(_006_),
    .Q(state[1])
  );
  (* src = "pixelSensorFsm.v:102" *)
  \$_DLATCH_P_  _736_ (
    .D(_005_[2]),
    .E(_006_),
    .Q(state[2])
  );
  (* src = "pixelSensorFsm.v:102" *)
  \$_DLATCH_P_  _737_ (
    .D(_003_[0]),
    .E(_007_),
    .Q(next_state[0])
  );
  (* src = "pixelSensorFsm.v:102" *)
  \$_DLATCH_P_  _738_ (
    .D(_003_[1]),
    .E(_007_),
    .Q(next_state[1])
  );
  (* src = "pixelSensorFsm.v:102" *)
  \$_DLATCH_P_  _739_ (
    .D(1'h0),
    .E(_007_),
    .Q(next_state[2])
  );
  (* src = "pixelSensorFsm.v:102" *)
  \$_DLATCH_P_  _740_ (
    .D(1'h0),
    .E(reset),
    .Q(convert)
  );
  assign _182_ = _509_;
  assign _184_ = _511_;
  assign _476_ = counter[0];
  assign _477_ = counter[2];
  assign _478_ = counter[4];
  assign _479_ = counter[6];
  assign _480_ = counter[8];
  assign _481_ = counter[10];
  assign _482_ = counter[12];
  assign _483_ = counter[14];
  assign _484_ = counter[16];
  assign _485_ = counter[18];
  assign _486_ = counter[20];
  assign _487_ = counter[22];
  assign _488_ = counter[24];
  assign _489_ = counter[26];
  assign _490_ = counter[28];
  assign _491_ = counter[1];
  assign _492_ = counter[3];
  assign _493_ = counter[5];
  assign _494_ = counter[7];
  assign _495_ = counter[9];
  assign _496_ = counter[11];
  assign _497_ = counter[13];
  assign _498_ = counter[15];
  assign _499_ = counter[17];
  assign _500_ = counter[19];
  assign _501_ = counter[21];
  assign _502_ = counter[23];
  assign _503_ = counter[25];
  assign _504_ = counter[27];
  assign _505_ = counter[29];
  assign _506_ = counter[30];
  assign _507_ = counter[31];
  assign _267_ = clk;
  assign _517_ = _266_;
  assign counter[0] = _269_;
  assign counter[1] = _280_;
  assign _474_ = state[1];
  assign _475_ = state[2];
  assign _473_ = state[0];
  assign counter[3] = _294_;
  assign counter[2] = _291_;
  assign counter[5] = _296_;
  assign counter[4] = _295_;
  assign counter[7] = _298_;
  assign counter[6] = _297_;
  assign counter[9] = _300_;
  assign counter[8] = _299_;
  assign counter[11] = _271_;
  assign counter[10] = _270_;
  assign counter[13] = _273_;
  assign counter[12] = _272_;
  assign counter[15] = _275_;
  assign counter[14] = _274_;
  assign counter[17] = _277_;
  assign counter[16] = _276_;
  assign counter[19] = _279_;
  assign counter[18] = _278_;
  assign counter[21] = _282_;
  assign counter[20] = _281_;
  assign counter[23] = _284_;
  assign counter[22] = _283_;
  assign counter[25] = _286_;
  assign counter[24] = _285_;
  assign counter[27] = _288_;
  assign counter[26] = _287_;
  assign counter[29] = _290_;
  assign counter[28] = _289_;
  assign counter[31] = _293_;
  assign counter[30] = _292_;
  assign _468_ = next_state[0];
  assign _469_ = next_state[1];
  assign _470_ = next_state[2];
  assign _003_[0] = _221_;
  assign _472_ = reset;
  assign _003_[1] = _222_;
  assign _005_[0] = _224_;
  assign _005_[1] = _225_;
  assign _005_[2] = _226_;
  assign _268_ = convert;
  assign _261_ = _509_;
  assign _000_ = _218_;
  assign _302_ = expose;
  assign _262_ = _511_;
  assign _002_ = _220_;
  assign _301_ = erase;
  assign _001_ = _219_;
  assign _471_ = read;
  assign _004_ = _223_;
  assign _006_ = _227_;
  assign _007_ = _228_;
  assign _514_ = _263_;
  assign _515_ = _264_;
  assign _516_ = _265_;
  assign _229_ = _476_;
  assign _230_ = _477_;
  assign _231_ = _478_;
  assign _232_ = _479_;
  assign _233_ = _480_;
  assign _234_ = _481_;
  assign _235_ = _482_;
  assign _236_ = _483_;
  assign _237_ = _484_;
  assign _238_ = _485_;
  assign _239_ = _486_;
  assign _240_ = _487_;
  assign _241_ = _488_;
  assign _242_ = _489_;
  assign _243_ = _490_;
  assign _244_ = _491_;
  assign _245_ = _492_;
  assign _246_ = _493_;
  assign _247_ = _494_;
  assign _248_ = _495_;
  assign _249_ = _496_;
  assign _250_ = _497_;
  assign _251_ = _498_;
  assign _252_ = _499_;
  assign _253_ = _500_;
  assign _254_ = _501_;
  assign _255_ = _502_;
  assign _256_ = _503_;
  assign _257_ = _504_;
  assign _258_ = _505_;
  assign _259_ = _506_;
  assign _260_ = _507_;
endmodule
